name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Publish to Maven Local
      run: ./gradlew build publishToMavenLocal --stacktrace -PlocalPublish
    - uses: actions/upload-artifact@v2
      with:
        name: Maven
        path: ~/.m2/

  publish:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        shell: bash
        run: |
          ./gradlew publishPlugin \
            -Pgradle.publish.key=$GRADLE_PUBLISH_KEY \
            -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
